camel:
  component:
    kafka:
      brokers: localhost:9092
  kafka:
    consumer:
      autoOffsetReset: earliest #latest
      maxPollRecords: 5
      maxPollIntervalMs: 60000
      config: "autoOffsetReset=${camel.kafka.consumer.autoOffsetReset}&maxPollRecords=${camel.kafka.consumer.maxPollRecords}&maxPollIntervalMs=${camel.kafka.consumer.maxPollIntervalMs}"
    paymentInstructionTopic: "input"
    messageProcessingControlEventTopic: "message-processing-control-event"
    routes:
      paymentInstructionProcessingRoute:
        groupId: "groupId=payment-instruction-processing-route-group"
        enable: true
        url: "kafka:${camel.kafka.paymentInstructionTopic}?brokers=${camel.component.kafka.brokers}&${camel.kafka.routes.paymentInstructionProcessingRoute.groupId}&${camel.kafka.consumer.config}"
      messageProcessingControlEventRoute:
        groupId: "groupId=message-processing-control-event-group-${random.uuid}"
        enable: true
        url: "kafka:${camel.kafka.messageProcessingControlEventTopic}?brokers=${camel.component.kafka.brokers}&${camel.kafka.routes.messageProcessingControlEventRoute.groupId}&${camel.kafka.consumer.config}"

route.throttling:
  throttleRate: 1
  timePeriodMillis: 10000


